[package]
name = "smart_gamblers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markov = "1.1.0"
scottish_names = "0.2.2"
rand = "0.8.4"
titlecase = "1.1.0"